
project_id = "isqyxkfodhgxzcyplbkg"

[functions.demo-notification]
verify_jwt = false

[functions.contact]
verify_jwt = false

[functions.wellness-provider]
verify_jwt = false

[functions.intelligent-chat]
verify_jwt = false

[functions.cv-submission]
verify_jwt = false
